all: atom_warehouse supplier_atom

atom_warehouse: atom_warehouse.cpp
	g++ -Wall -o atom_warehouse atom_warehouse.cpp

supplier_atom: supplier_atom.cpp
	g++ -Wall -o supplier_atom supplier_atom.cpp

clean:
	rm -f atom_warehouse supplier_atom
